databases:
  - name: integrationland_db
    databaseName: land_soil_system
    user: admin
    plan: free

services:
  - type: web
    name: integrationland
    runtime: docker
    dockerContext: integrationland
    dockerfile: Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: integrationland_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: integrationland_db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: integrationland_db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: integrationland_db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: integrationland_db
          property: password
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx384m -Xms384m"
